core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from . import views
from .forms import LoginForm

app_name='core'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact', views.contact, name='contact'),
    path('signup', views.signup, name='signup'),
    path('login', LoginView.as_view(
        template_name='core/login.html',
        authentication_form=LoginForm), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),

]

item/urls.py
from django.urls import path
from . import views

app_name='item'
urlpatterns = [
    path('items', views.items, name='items'),
    path('new', views.new, name='new'),
    path('item/<int:pk>',views.detail, name='detail'),
    path('item/delete/<int:pk>',views.delete, name='delete'),
    path('item/edit/<int:pk>',views.edit, name='edit'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('', include('dashboard.urls'), name='dashboard'),
    path('inbox/', include('conversation.urls'), name='conversation'),
    path('', include('item.urls'), name='item'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


# -------------
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Enter Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))        

core/views.py
from django.shortcuts import redirect, render
from item.models import Category, Item
from .forms import SignUpForm
# Create your views here.

def index(request):
    items = Item.objects.filter(is_sold=False)[:6]
    categories = Category.objects.all()

    context = {
        'items' : items,
        'categories' : categories,   
    }
    return render(request, 'core/index.html', context)


def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login')
    else:
        form = SignUpForm()

    return render(request, 'core/signup.html', {
        'form' : form
    })

core/templates/core/contact.html
{% extends 'base.html' %}
{% block title %}Welcome{% endblock title %}
{% block body %}
    <div class="px-6 py-6">
        <h1 class="text-center text-xl font-bold">Contact Page</h1>
    </div>
{% endblock body %}

core/templates/core/index.html
{% extends 'base.html' %}
{% block title %}Welcome{% endblock title %}
{% block body %}
    <div class="px-6 py-6">
        <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
            <h2 class="mb-12 text-2xl text-center">Newest items</h2>
        </div>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
            <h2 class="mb-12 text-2xl text-center">Categories</h2>
    
            <div class="grid grid-cols-3 gap-3">
                {% for category in categories %}
                    <div>
                        <a href="#">
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ category.name }}</h2>
                                <!-- items is related name in Item -->
                                <p class="text-gray-500">{{ category.items.count }} items</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock body %}

core/templates/core/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block body %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="POST">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button type="submit" class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}

{% block body %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="POST">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Confirm password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button type="submit" class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}